---
- name: Configure webserver with Nginx
  hosts: dev
  become: True
  vars:
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
    server_port: "{{ hostvars[inventory_hostname][sdms_environment]['nginx_port'] }}"
    sdms_environment: "{{ sdms_environment }}"
  tasks:
    - name: install Nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600

    - name: copy Nginx config file
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}

    - name: enable configuration
      file: src={{ conf_file }} dest=/etc/nginx/sites-enabled/default state=link

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart Nginx
      service: name=nginx state=restarted