VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define "vagrant1" do | vagrant1|
    vagrant1.vm.box = "ubuntu/trusty64"
    vagrant1.vm.network "forwarded_port", guest: 9090, host: 8080
    vagrant1.vm.network "forwarded_port", guest: 9190, host: 8180
    vagrant1.vm.network "forwarded_port", guest: 9290, host: 8280
  end
  config.vm.define "vagrant2" do | vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64"
    vagrant2.vm.network "forwarded_port", guest: 9090, host: 8081
    vagrant2.vm.network "forwarded_port", guest: 9190, host: 8181
    vagrant2.vm.network "forwarded_port", guest: 9290, host: 8281
  end
end
